/**
 * Test Report Generator
 * Generates HTML reports from test results
 */

import * as path from 'path';
import * as fs from 'fs';
import { TestResult, VisualTestResult } from '../types';
import { PlaybackResult } from '../player';

export interface ReportOptions {
  outputDir?: string;
  title?: string;
  includeScreenshots?: boolean;
}

export class ReportGenerator {
  private options: ReportOptions;

  constructor(options: ReportOptions = {}) {
    this.options = {
      outputDir: options.outputDir || '.qa-agent/reports',
      title: options.title || 'QA-Agent 测试报告',
      includeScreenshots: options.includeScreenshots ?? true,
    };
  }

  /**
   * Generate HTML report from test result
   */
  async generateTestReport(result: TestResult, name: string): Promise<string> {
    const html = this.generateTestHtml(result, name);
    return await this.saveReport(html, `test-${name}-${Date.now()}.html`);
  }

  /**
   * Generate HTML report from visual test result
   */
  async generateVisualReport(result: VisualTestResult, name: string): Promise<string> {
    const html = this.generateVisualHtml(result, name);
    return await this.saveReport(html, `visual-${name}-${Date.now()}.html`);
  }

  /**
   * Generate HTML report from playback result
   */
  async generatePlaybackReport(result: PlaybackResult, name: string): Promise<string> {
    const html = this.generatePlaybackHtml(result, name);
    return await this.saveReport(html, `playback-${name}-${Date.now()}.html`);
  }

  /**
   * Generate combined report
   */
  async generateCombinedReport(results: {
    tests?: Array<{ result: TestResult; name: string }>;
    visuals?: Array<{ result: VisualTestResult; name: string }>;
    playbacks?: Array<{ result: PlaybackResult; name: string }>;
  }): Promise<string> {
    const html = this.generateCombinedHtml(results);
    return await this.saveReport(html, `combined-${Date.now()}.html`);
  }

  /**
   * Generate test HTML
   */
  private generateTestHtml(result: TestResult, name: string): string {
    const status = result.success ? 'passed' : 'failed';
    const statusIcon = result.success ? '✓' : '✗';
    const statusColor = result.success ? '#10b981' : '#ef4444';

    return `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.options.title} - ${name}</title>
  <style>
    ${this.getBaseStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header class="header">
      <h1>${this.options.title}</h1>
      <div class="meta">
        <span class="status ${status}">${statusIcon} ${status.toUpperCase()}</span>
        <span class="duration">耗时: ${result.duration}ms</span>
      </div>
    </header>

    <main class="content">
      <section class="summary">
        <h2>测试概览</h2>
        <div class="stats">
          <div class="stat">
            <span class="stat-value">${result.steps.length}</span>
            <span class="stat-label">总步骤</span>
          </div>
          <div class="stat">
            <span class="stat-value">${result.steps.filter(s => s.success).length}</span>
            <span class="stat-label">通过</span>
          </div>
          <div class="stat">
            <span class="stat-value">${result.steps.filter(s => !s.success).length}</span>
            <span class="stat-label">失败</span>
          </div>
        </div>
      </section>

      <section class="steps">
        <h2>测试步骤</h2>
        ${result.steps.map((step, i) => `
          <div class="step ${step.success ? 'passed' : 'failed'}">
            <div class="step-header">
              <span class="step-number">${i + 1}</span>
              <span class="step-action">${step.action}</span>
              <span class="step-status">${step.success ? '✓' : '✗'}</span>
            </div>
            ${step.selector ? `<div class="step-detail">选择器: <code>${step.selector}</code></div>` : ''}
            ${step.value ? `<div class="step-detail">值: <code>${step.value}</code></div>` : ''}
            ${step.error ? `<div class="step-error">${step.error}</div>` : ''}
          </div>
        `).join('')}
      </section>

      ${result.error ? `
        <section class="error-section">
          <h2>错误信息</h2>
          <pre class="error-message">${result.error}</pre>
        </section>
      ` : ''}
    </main>

    <footer class="footer">
      <p>Generated by QA-Agent at ${new Date().toLocaleString()}</p>
    </footer>
  </div>
</body>
</html>
    `.trim();
  }

  /**
   * Generate visual test HTML
   */
  private generateVisualHtml(result: VisualTestResult, name: string): string {
    const status = result.passed ? 'passed' : 'failed';
    const statusIcon = result.passed ? '✓' : '✗';

    return `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.options.title} - ${name}</title>
  <style>
    ${this.getBaseStyles()}
    .diff-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 1rem;
    }
    .diff-card {
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 1rem;
    }
    .diff-card.matched {
      border-color: #10b981;
    }
    .diff-card.mismatched {
      border-color: #ef4444;
    }
  </style>
</head>
<body>
  <div class="container">
    <header class="header">
      <h1>${this.options.title}</h1>
      <div class="meta">
        <span class="status ${status}">${statusIcon} ${status.toUpperCase()}</span>
        <span class="duration">耗时: ${result.duration}ms</span>
      </div>
    </header>

    <main class="content">
      <section class="summary">
        <h2>视觉测试概览</h2>
        <div class="stats">
          <div class="stat">
            <span class="stat-value">${result.results.length}</span>
            <span class="stat-label">总测试</span>
          </div>
          <div class="stat">
            <span class="stat-value">${result.results.filter(r => r.match).length}</span>
            <span class="stat-label">通过</span>
          </div>
          <div class="stat">
            <span class="stat-value">${result.results.filter(r => !r.match).length}</span>
            <span class="stat-label">失败</span>
          </div>
        </div>
      </section>

      <section class="diffs">
        <h2>对比结果</h2>
        <div class="diff-grid">
          ${result.results.map(r => `
            <div class="diff-card ${r.match ? 'matched' : 'mismatched'}">
              <h3>${r.name}</h3>
              <div class="diff-info">
                <span class="diff-percent ${r.match ? 'passed' : 'failed'}">
                  ${r.match ? '✓' : '✗'} ${r.diffPercentage.toFixed(2)}% 差异
                </span>
                ${r.selector ? `<div>选择器: <code>${r.selector}</code></div>` : ''}
              </div>
              <div class="diff-paths">
                <div>基线: ${r.baselinePath}</div>
                <div>当前: ${r.currentPath}</div>
                ${r.diffPath ? `<div>差异: ${r.diffPath}</div>` : ''}
              </div>
            </div>
          `).join('')}
        </div>
      </section>
    </main>

    <footer class="footer">
      <p>Generated by QA-Agent at ${new Date().toLocaleString()}</p>
    </footer>
  </div>
</body>
</html>
    `.trim();
  }

  /**
   * Generate playback HTML
   */
  private generatePlaybackHtml(result: PlaybackResult, name: string): string {
    const status = result.success ? 'passed' : 'failed';
    const statusIcon = result.success ? '✓' : '✗';

    return `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.options.title} - ${name}</title>
  <style>
    ${this.getBaseStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header class="header">
      <h1>${this.options.title}</h1>
      <div class="meta">
        <span class="status ${status}">${statusIcon} ${status.toUpperCase()}</span>
        <span class="duration">耗时: ${result.duration}ms</span>
      </div>
    </header>

    <main class="content">
      <section class="summary">
        <h2>回放概览</h2>
        <div class="stats">
          <div class="stat">
            <span class="stat-value">${result.totalSteps}</span>
            <span class="stat-label">总步骤</span>
          </div>
          <div class="stat">
            <span class="stat-value">${result.executedSteps}</span>
            <span class="stat-label">执行</span>
          </div>
          <div class="stat">
            <span class="stat-value">${result.errors.length}</span>
            <span class="stat-label">错误</span>
          </div>
        </div>
      </section>

      ${result.errors.length > 0 ? `
        <section class="errors">
          <h2>错误详情</h2>
          ${result.errors.map((e: any) => `
            <div class="error-card">
              <h3>步骤 ${e.stepIndex + 1}</h3>
              <div class="error-type">${e.step.type}</div>
              ${e.step.selector ? `<div>选择器: <code>${e.step.selector}</code></div>` : ''}
              ${e.step.value ? `<div>值: <code>${e.step.value}</code></div>` : ''}
              <pre class="error-message">${e.error}</pre>
            </div>
          `).join('')}
        </section>
      ` : ''}
    </main>

    <footer class="footer">
      <p>Generated by QA-Agent at ${new Date().toLocaleString()}</p>
    </footer>
  </div>
</body>
</html>
    `.trim();
  }

  /**
   * Generate combined HTML
   */
  private generateCombinedHtml(results: {
    tests?: Array<{ result: TestResult; name: string }>;
    visuals?: Array<{ result: VisualTestResult; name: string }>;
    playbacks?: Array<{ result: PlaybackResult; name: string }>;
  }): string {
    const allPassed = 
      (results.tests?.every(t => t.result.success) ?? true) &&
      (results.visuals?.every(v => v.result.passed) ?? true) &&
      (results.playbacks?.every(p => p.result.success) ?? true);

    const status = allPassed ? 'passed' : 'failed';
    const statusIcon = allPassed ? '✓' : '✗';

    return `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.options.title}</title>
  <style>
    ${this.getBaseStyles()}
  </style>
</head>
<body>
  <div class="container">
    <header class="header">
      <h1>${this.options.title}</h1>
      <div class="meta">
        <span class="status ${status}">${statusIcon} ${status.toUpperCase()}</span>
      </div>
    </header>

    <main class="content">
      ${(results.tests?.length ?? 0) > 0 ? `
        <section class="test-section">
          <h2>E2E 测试</h2>
          ${results.tests!.map(t => `
            <div class="test-result ${t.result.success ? 'passed' : 'failed'}">
              <h3>${t.name} ${t.result.success ? '✓' : '✗'}</h3>
              <div>${t.result.steps.length} 步骤, ${t.result.duration}ms</div>
            </div>
          `).join('')}
        </section>
      ` : ''}

      ${(results.visuals?.length ?? 0) > 0 ? `
        <section class="visual-section">
          <h2>视觉测试</h2>
          ${results.visuals!.map(v => `
            <div class="visual-result ${v.result.passed ? 'passed' : 'failed'}">
              <h3>${v.name} ${v.result.passed ? '✓' : '✗'}</h3>
              <div>${v.result.results.length} 测试, ${v.result.duration}ms</div>
            </div>
          `).join('')}
        </section>
      ` : ''}

      ${(results.playbacks?.length ?? 0) > 0 ? `
        <section class="playback-section">
          <h2>回放测试</h2>
          ${results.playbacks!.map(p => `
            <div class="playback-result ${p.result.success ? 'passed' : 'failed'}">
              <h3>${p.name} ${p.result.success ? '✓' : '✗'}</h3>
              <div>${p.result.executedSteps}/${p.result.totalSteps} 步骤, ${p.result.duration}ms</div>
            </div>
          `).join('')}
        </section>
      ` : ''}
    </main>

    <footer class="footer">
      <p>Generated by QA-Agent at ${new Date().toLocaleString()}</p>
    </footer>
  </div>
</body>
</html>
    `.trim();
  }

  /**
   * Get base CSS styles
   */
  private getBaseStyles(): string {
    return `
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        background: #f3f4f6;
        color: #1f2937;
        line-height: 1.6;
      }
      .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 2rem;
      }
      .header {
        text-align: center;
        margin-bottom: 2rem;
      }
      .header h1 {
        font-size: 2rem;
        margin-bottom: 1rem;
      }
      .meta {
        display: flex;
        justify-content: center;
        gap: 1rem;
        align-items: center;
      }
      .status {
        padding: 0.5rem 1rem;
        border-radius: 9999px;
        font-weight: 600;
      }
      .status.passed {
        background: #d1fae5;
        color: #065f46;
      }
      .status.failed {
        background: #fee2e2;
        color: #991b1b;
      }
      .duration {
        color: #6b7280;
      }
      .content {
        background: white;
        border-radius: 8px;
        padding: 2rem;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
      }
      section {
        margin-bottom: 2rem;
      }
      section:last-child {
        margin-bottom: 0;
      }
      h2 {
        font-size: 1.5rem;
        margin-bottom: 1rem;
        padding-bottom: 0.5rem;
        border-bottom: 2px solid #e5e7eb;
      }
      .stats {
        display: flex;
        gap: 2rem;
      }
      .stat {
        text-align: center;
      }
      .stat-value {
        display: block;
        font-size: 2rem;
        font-weight: 700;
        color: #1f2937;
      }
      .stat-label {
        color: #6b7280;
        font-size: 0.875rem;
      }
      .step {
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 1rem;
        margin-bottom: 0.5rem;
      }
      .step.passed {
        border-left: 4px solid #10b981;
      }
      .step.failed {
        border-left: 4px solid #ef4444;
      }
      .step-header {
        display: flex;
        align-items: center;
        gap: 0.5rem;
      }
      .step-number {
        background: #e5e7eb;
        width: 24px;
        height: 24px;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 0.75rem;
        font-weight: 600;
      }
      .step-action {
        flex: 1;
      }
      .step-status {
        font-weight: 600;
      }
      .step-detail {
        margin-top: 0.5rem;
        font-size: 0.875rem;
        color: #6b7280;
      }
      .step-detail code {
        background: #f3f4f6;
        padding: 0.125rem 0.25rem;
        border-radius: 4px;
        font-family: monospace;
      }
      .step-error {
        margin-top: 0.5rem;
        padding: 0.5rem;
        background: #fee2e2;
        color: #991b1b;
        border-radius: 4px;
        font-size: 0.875rem;
      }
      .error-section {
        background: #fef2f2;
        padding: 1rem;
        border-radius: 8px;
      }
      .error-message {
        background: #f3f4f6;
        padding: 1rem;
        border-radius: 4px;
        overflow-x: auto;
        font-family: monospace;
        font-size: 0.875rem;
      }
      .footer {
        text-align: center;
        margin-top: 2rem;
        color: #6b7280;
        font-size: 0.875rem;
      }
    `;
  }

  /**
   * Save report to file
   */
  private async saveReport(html: string, filename: string): Promise<string> {
    const outputDir = this.options.outputDir!;
    
    if (!fs.existsSync(outputDir)) {
      await fs.promises.mkdir(outputDir, { recursive: true });
    }

    const filepath = path.join(outputDir, filename);
    await fs.promises.writeFile(filepath, html);

    return filepath;
  }
}
