/**
 * CI/CD Integration
 * Provides CI configuration generation for 4 platforms
 *
 * 4 个平台的输出（GitHub Actions / GitLab / Jenkins / CircleCI）
 * 80% 是同样的步骤：装依赖 → diagnose → audit → 归档 → critical gate。
 * 把共性抽到 `stepsFor()`，平台差异只留缩进/语法/YAML 结构。
 */

import * as fs from 'fs/promises';
import * as path from 'path';

export interface CIConfig {
  platform: 'github' | 'gitlab' | 'jenkins' | 'circleci';
  triggers: {
    push?: boolean;
    pullRequest?: boolean;
    schedule?: string;
  };
  skills: string[];
  failOn: 'critical' | 'warning' | 'any';
  outputFormat: 'json' | 'junit' | 'sarif';
  cache: boolean;
  nodeVersion?: string;
}

export const DEFAULT_CI_CONFIG: CIConfig = {
  platform: 'github',
  triggers: {
    push: true,
    pullRequest: true,
    schedule: '0 0 * * *',
  },
  skills: ['e2e', 'a11y', 'performance', 'security'],
  failOn: 'critical',
  outputFormat: 'json',
  cache: true,
  nodeVersion: '20',
};

/**
 * 通用步骤：所有平台都需要跑的 5 件事。
 * 平台渲染器按各自语法映射即可。
 */
function buildSteps(config: CIConfig) {
  const skills = config.skills.join(',');
  return {
    setup: [
      'checkout / clone project',
      config.cache ? 'cache dependencies' : 'skip cache',
    ],
    install: 'bun install',
    diagnose:
      `bunx qa-agent diagnose ` +
      `--skills ${skills} ` +
      `--output json ` +
      `--output-file qa-report.json ` +
      `--fail-on ${config.failOn} ` +
      `--ci`,
    audit:
      `bunx qa-agent audit ` +
      `--output json ` +
      `--output-file qa-audit.json ` +
      `--ci`,
    artifacts: ['qa-report.json', 'qa-audit.json', '.qa-agent/reports/'],
    qualityGate: {
      jsonPath: 'qa-report.json',
      field: '.summary.critical',
      condition: '> 0',
    },
  };
}

// =================== GitHub Actions ===================

export function generateGitHubActions(config: CIConfig): string {
  const s = buildSteps(config);
  const branches = ['main', 'master', 'develop'];

  return `# QA-Agent Quality Check
# Generated by qa-agent ci init

name: QA-Agent

on:
  push:
    branches: [${branches.join(', ')}]
  pull_request:
    branches: [${branches.join(', ')}]
  schedule:
    - cron: '${config.triggers.schedule || '0 0 * * *'}'
  workflow_dispatch:

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: ${s.install}

      - name: Run QA-Agent diagnose
        run: ${s.diagnose.replace(/ /g, ' \\\n          ')}
        continue-on-error: true

      - name: Run QA-Agent audit
        run: ${s.audit.replace(/ /g, ' \\\n          ')}
        continue-on-error: true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: qa-reports
          path: |
            ${s.artifacts.join('\n            ')}
          retention-days: 30

      - name: Check quality gate
        run: |
          if [ -f ${s.qualityGate.jsonPath} ]; then
            CRITICAL=$(cat ${s.qualityGate.jsonPath} | jq '${s.qualityGate.field} // 0')
            if [ "$CRITICAL" -gt 0 ]; then
              echo "::error::Found $CRITICAL critical issues"
              exit 1
            fi
          fi
`;
}

// =================== GitLab CI ===================

export function generateGitLabCI(config: CIConfig): string {
  const s = buildSteps(config);

  return `# QA-Agent Quality Check
# Generated by qa-agent ci init

stages:
  - quality

qa-agent:
  stage: quality
  image: oven/bun:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - ${s.install}
    - ${s.diagnose} || true
    - ${s.audit} || true
  artifacts:
    when: always
    paths:
      - ${s.artifacts.join('\n      - ')}
    expire_in: 30 days
  after_script:
    - |
      if [ -f ${s.qualityGate.jsonPath} ]; then
        CRITICAL=$(cat ${s.qualityGate.jsonPath} | jq '${s.qualityGate.field} // 0')
        if [ "$CRITICAL" -gt 0 ]; then
          echo "Found $CRITICAL critical issues"
          exit 1
        fi
      fi
`;
}

// =================== Jenkinsfile ===================

export function generateJenkinsfile(config: CIConfig): string {
  const s = buildSteps(config);

  return `// QA-Agent Quality Check
// Generated by qa-agent ci init

pipeline {
  agent any

  tools {
    nodejs 'NodeJS-${config.nodeVersion || '20'}'
  }

  stages {
    stage('Install') {
      steps {
        sh 'npm install -g bun'
        sh '${s.install}'
      }
    }

    stage('QA-Agent Diagnose') {
      steps {
        sh '''
          ${s.diagnose} || true
        '''
      }
    }

    stage('QA-Agent Audit') {
      steps {
        sh '''
          ${s.audit} || true
        '''
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'qa-*.json, .qa-agent/reports/**', allowEmptyArchive: true
    }
    failure {
      echo 'QA-Agent found critical issues!'
    }
    success {
      echo 'QA-Agent check passed!'
    }
  }
}
`;
}

// =================== CircleCI ===================

export function generateCircleCI(config: CIConfig): string {
  const s = buildSteps(config);

  return `# QA-Agent Quality Check
# Generated by qa-agent ci init

version: 2.1

jobs:
  qa-check:
    docker:
      - image: cimg/node:${config.nodeVersion || '20'}.0
    steps:
      - checkout

      - run:
          name: Install Bun
          command: |
            curl -fsSL https://bun.sh/install | bash
            echo 'export PATH="$HOME/.bun/bin:$PATH"' >> $BASH_ENV

      - run:
          name: Install dependencies
          command: ${s.install}

      - run:
          name: Run QA-Agent diagnose
          command: ${s.diagnose} || true

      - run:
          name: Run QA-Agent audit
          command: ${s.audit} || true

${s.artifacts.map((a) => `      - store_artifacts:\n          path: ${a}`).join('\n')}

      - run:
          name: Check quality gate
          command: |
            if [ -f ${s.qualityGate.jsonPath} ]; then
              CRITICAL=$(cat ${s.qualityGate.jsonPath} | jq '${s.qualityGate.field} // 0')
              if [ "$CRITICAL" -gt 0 ]; then
                echo "Found $CRITICAL critical issues"
                exit 1
              fi
            fi

workflows:
  version: 2
  quality:
    jobs:
      - qa-check
`;
}

// =================== Public dispatchers ===================

export function generateCIConfig(config: CIConfig): { filename: string; content: string } {
  switch (config.platform) {
    case 'github':
      return { filename: '.github/workflows/qa-agent.yml', content: generateGitHubActions(config) };
    case 'gitlab':
      return { filename: '.gitlab-ci.yml', content: generateGitLabCI(config) };
    case 'jenkins':
      return { filename: 'Jenkinsfile', content: generateJenkinsfile(config) };
    case 'circleci':
      return { filename: '.circleci/config.yml', content: generateCircleCI(config) };
    default: {
      const _exhaustive: never = config.platform;
      throw new Error(`Unsupported CI platform: ${_exhaustive}`);
    }
  }
}

export async function writeCIConfig(projectPath: string, config: CIConfig): Promise<string> {
  const { filename, content } = generateCIConfig(config);
  const fullPath = path.join(projectPath, filename);
  await fs.mkdir(path.dirname(fullPath), { recursive: true });
  await fs.writeFile(fullPath, content, 'utf-8');
  return fullPath;
}

export async function detectCIPlatform(projectPath: string): Promise<CIConfig['platform'] | null> {
  const checks: Array<{ file: string; platform: CIConfig['platform'] }> = [
    { file: '.github/workflows', platform: 'github' },
    { file: '.gitlab-ci.yml', platform: 'gitlab' },
    { file: 'Jenkinsfile', platform: 'jenkins' },
    { file: '.circleci/config.yml', platform: 'circleci' },
  ];

  for (const { file, platform } of checks) {
    try {
      await fs.access(path.join(projectPath, file));
      return platform;
    } catch {
      // 继续探下一个
    }
  }
  return null;
}
