/**
 * CI/CD Integration
 * Provides CI configuration generation and CI-specific modes
 */

import * as fs from 'fs/promises';
import * as path from 'path';

export interface CIConfig {
  platform: 'github' | 'gitlab' | 'jenkins' | 'circleci';
  triggers: {
    push?: boolean;
    pullRequest?: boolean;
    schedule?: string;
  };
  skills: string[];
  failOn: 'critical' | 'warning' | 'any';
  outputFormat: 'json' | 'junit' | 'sarif';
  cache: boolean;
  nodeVersion?: string;
}

export const DEFAULT_CI_CONFIG: CIConfig = {
  platform: 'github',
  triggers: {
    push: true,
    pullRequest: true,
    schedule: '0 0 * * *', // Daily at midnight
  },
  skills: ['e2e', 'a11y', 'performance', 'security'],
  failOn: 'critical',
  outputFormat: 'json',
  cache: true,
  nodeVersion: '20',
};

/**
 * Generate GitHub Actions workflow
 */
export function generateGitHubActions(config: CIConfig): string {
  const skills = config.skills.join(',');
  
  return `# QA-Agent Quality Check
# Generated by qa-agent ci init

name: QA-Agent

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  schedule:
    - cron: '${config.triggers.schedule || '0 0 * * *'}'
  workflow_dispatch:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run QA-Agent diagnose
        run: bunx qa-agent diagnose \\
          --skills ${skills} \\
          --output json \\
          --output-file qa-report.json \\
          --fail-on ${config.failOn} \\
          --ci
        continue-on-error: true

      - name: Run QA-Agent audit
        run: bunx qa-agent audit \\
          --output json \\
          --output-file qa-audit.json \\
          --ci
        continue-on-error: true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: qa-reports
          path: |
            qa-report.json
            qa-audit.json
            .qa-agent/reports/
          retention-days: 30

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            try {
              const report = JSON.parse(fs.readFileSync('qa-report.json', 'utf8'));
              const summary = report.summary || {};
              
              const body = \\\`## QA-Agent Report
              
              | Metric | Value |
              |--------|-------|
              | Score | \${summary.score}/100 |
              | Grade | \${summary.grade} |
              | Issues | \${summary.totalIssues} |
              | Critical | \${summary.critical} |
              | Warnings | \${summary.warning} |
              
              \\\${summary.critical > 0 ? '⚠️ **Critical issues found!**' : '✅ No critical issues.'}
              \\\`;
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            } catch (e) {
              console.log('Could not post comment:', e.message);
            }

      - name: Check quality gate
        run: |
          if [ -f qa-report.json ]; then
            CRITICAL=$(cat qa-report.json | jq '.summary.critical // 0')
            if [ "$CRITICAL" -gt 0 ]; then
              echo "::error::Found $CRITICAL critical issues"
              exit 1
            fi
          fi
`;
}

/**
 * Generate GitLab CI configuration
 */
export function generateGitLabCI(config: CIConfig): string {
  const skills = config.skills.join(',');
  
  return `# QA-Agent Quality Check
# Generated by qa-agent ci init

stages:
  - quality

qa-agent:
  stage: quality
  image: oven/bun:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - bun install
    - bunx qa-agent diagnose --skills ${skills} --output json --output-file qa-report.json --fail-on ${config.failOn} --ci || true
    - bunx qa-agent audit --output json --output-file qa-audit.json --ci || true
  artifacts:
    when: always
    paths:
      - qa-report.json
      - qa-audit.json
      - .qa-agent/reports/
    expire_in: 30 days
  after_script:
    - |
      if [ -f qa-report.json ]; then
        CRITICAL=$(cat qa-report.json | jq '.summary.critical // 0')
        if [ "$CRITICAL" -gt 0 ]; then
          echo "Found $CRITICAL critical issues"
          exit 1
        fi
      fi
`;
}

/**
 * Generate Jenkinsfile
 */
export function generateJenkinsfile(config: CIConfig): string {
  const skills = config.skills.join(',');
  
  return `// QA-Agent Quality Check
// Generated by qa-agent ci init

pipeline {
  agent any
  
  tools {
    nodejs 'NodeJS-20'
  }
  
  stages {
    stage('Install') {
      steps {
        sh 'npm install -g bun'
        sh 'bun install'
      }
    }
    
    stage('QA-Agent Diagnose') {
      steps {
        sh '''
          bunx qa-agent diagnose \\
            --skills ${skills} \\
            --output json \\
            --output-file qa-report.json \\
            --fail-on ${config.failOn} \\
            --ci || true
        '''
      }
    }
    
    stage('QA-Agent Audit') {
      steps {
        sh '''
          bunx qa-agent audit \\
            --output json \\
            --output-file qa-audit.json \\
            --ci || true
        '''
      }
    }
  }
  
  post {
    always {
      archiveArtifacts artifacts: 'qa-*.json, .qa-agent/reports/**', allowEmptyArchive: true
    }
    failure {
      echo 'QA-Agent found critical issues!'
    }
    success {
      echo 'QA-Agent check passed!'
    }
  }
}
`;
}

/**
 * Generate CircleCI configuration
 */
export function generateCircleCI(config: CIConfig): string {
  const skills = config.skills.join(',');
  
  return `# QA-Agent Quality Check
# Generated by qa-agent ci init

version: 2.1

jobs:
  qa-check:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      
      - run:
          name: Install Bun
          command: |
            curl -fsSL https://bun.sh/install | bash
            echo 'export PATH="$HOME/.bun/bin:$PATH"' >> $BASH_ENV
      
      - run:
          name: Install dependencies
          command: bun install
      
      - run:
          name: Run QA-Agent diagnose
          command: |
            bunx qa-agent diagnose \\
              --skills ${skills} \\
              --output json \\
              --output-file qa-report.json \\
              --fail-on ${config.failOn} \\
              --ci || true
      
      - run:
          name: Run QA-Agent audit
          command: |
            bunx qa-agent audit \\
              --output json \\
              --output-file qa-audit.json \\
              --ci || true
      
      - store_artifacts:
          path: qa-report.json
      - store_artifacts:
          path: qa-audit.json
      - store_artifacts:
          path: .qa-agent/reports
      
      - run:
          name: Check quality gate
          command: |
            if [ -f qa-report.json ]; then
              CRITICAL=$(cat qa-report.json | jq '.summary.critical // 0')
              if [ "$CRITICAL" -gt 0 ]; then
                echo "Found $CRITICAL critical issues"
                exit 1
              fi
            fi

workflows:
  version: 2
  quality:
    jobs:
      - qa-check
`;
}

/**
 * Generate CI configuration based on platform
 */
export function generateCIConfig(config: CIConfig): { filename: string; content: string } {
  switch (config.platform) {
    case 'github':
      return {
        filename: '.github/workflows/qa-agent.yml',
        content: generateGitHubActions(config),
      };
    case 'gitlab':
      return {
        filename: '.gitlab-ci.yml',
        content: generateGitLabCI(config),
      };
    case 'jenkins':
      return {
        filename: 'Jenkinsfile',
        content: generateJenkinsfile(config),
      };
    case 'circleci':
      return {
        filename: '.circleci/config.yml',
        content: generateCircleCI(config),
      };
    default:
      throw new Error(`Unsupported CI platform: ${config.platform}`);
  }
}

/**
 * Write CI configuration to project
 */
export async function writeCIConfig(
  projectPath: string,
  config: CIConfig
): Promise<string> {
  const { filename, content } = generateCIConfig(config);
  const fullPath = path.join(projectPath, filename);
  
  // Ensure directory exists
  const dir = path.dirname(fullPath);
  await fs.mkdir(dir, { recursive: true });
  
  // Write file
  await fs.writeFile(fullPath, content, 'utf-8');
  
  return fullPath;
}

/**
 * Detect CI platform from project
 */
export async function detectCIPlatform(projectPath: string): Promise<CIConfig['platform'] | null> {
  const checks: Array<{ file: string; platform: CIConfig['platform'] }> = [
    { file: '.github/workflows', platform: 'github' },
    { file: '.gitlab-ci.yml', platform: 'gitlab' },
    { file: 'Jenkinsfile', platform: 'jenkins' },
    { file: '.circleci/config.yml', platform: 'circleci' },
  ];

  for (const { file, platform } of checks) {
    try {
      const fullPath = path.join(projectPath, file);
      await fs.access(fullPath);
      return platform;
    } catch {
      // Not found, continue
    }
  }

  return null;
}
